# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test assignment and submit to Canvas

on: [push]

jobs:
  test:
    name: Pytest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pipenv
        pipenv install --dev --deploy
#    - name: Lint with flake8
#      run: |
#        # stop the build if there are Python syntax errors or undefined names
#        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
#        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
#        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pipenv run pytest --cov-report xml --cov-report term
    - name: CodeClimate Coverage
      uses: paambaati/codeclimate-action@v2.7.5
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      with:
        coverageLocations: ${{github.workspace}}/coverage.xml:coverage.py

  submit:
    needs: test
    name: Submit to Canvas
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pipenv
        pipenv install --deploy
    - name: Submission
      env:
        CANVAS_TOKEN: ${{ secrets.CANVAS_TOKEN }}
        CANVAS_COURSE_ID: 94811
        CANVAS_ASSIGNMENT_ID: 500790
        CANVAS_QUIZ_ID: 229920
        CANVAS_URL: https://canvas.harvard.edu
        CANVAS_AS_TEST_STUDENT: True
      run: |
        pipenv run python submit.py